czat2/czat/urls.py
# -*- coding: utf-8 -*-
# czat/urls.py

from django.conf.urls import url
from django.urls import reverse_lazy
from . import views  # import widoków aplikacji
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DeleteView
from czat.models import Wiadomosc


app_name = 'czat'  # przestrzeń nazw aplikacji
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^rejestruj/$', CreateView.as_view(
        template_name="rejestruj.html",
        form_class=UserCreationForm,)),
    url(r'^loguj/', auth_views.auth_login, {'template_name': 'loguj.html'}, name='loguj'),
    url(r'^wyloguj/', auth_views.auth_logout, {'next_page': reverse_lazy('czat:index')}, name='wyloguj'),
    url(r'^wiadomosci/', login_required(
        ListView.as_view(
            model=Wiadomosc,
            context_object_name="wiadomosci",
            paginate_by=2)),
        name='wiadomosci'),
    url(r'^dodaj/$', login_required(
            views.DodajWiadomosc.as_view(),
            login_url='/loguj'),
        name='dodaj'),
    url(r'^edytuj/(?P<k>\d+)', login_required(
            views.EdytujWiadomosc.as_view(),
            login_url="/loguj"),
        name="edytuj"),
    url(r'^usun/(?P<pk>\d+)', login_required(
        DeleteView.as_view(
            model=Wiadomosc,
            template_name='wiadomosc_usun.html',
            success_url='/wiadomosci'),
        login_url='/loguj'),
        name='usun'),
]

czat2/czat2/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^', include('czat.urls')),
    url(r'^admin/', admin.site.urls),
]

czat2/czat/models.py
# -*- coding: utf-8 -*-
# czat/models.py

from django.db import models
from django.contrib.auth.models import User


class Wiadomosc(models.Model):

    """Klasa reprezentująca wiadomość w systemie"""
    tekst = models.CharField('treść wiadomości', max_length=250)
    data_pub = models.DateTimeField('data publikacji', auto_now_add=True)
    autor = models.ForeignKey(User, on_delete=models.CASCADE, )

    class Meta:  # ustawienia dodatkowe
        verbose_name = u'wiadomość'  # nazwa obiektu w języku polskim
        verbose_name_plural = u'wiadomości'  # nazwa obiektów w l.m.
        ordering = ['data_pub']  # domyślne porządkowanie danych

    def __str__(self):
        return self.tekst  # "autoprezentacja"

czat2/czat/forms.py
# -*- coding: utf-8 -*-

from django.forms import ModelForm, TextInput
from czat.models import Wiadomosc


class EdytujWiadomoscForm(ModelForm):
    class Meta:
        model = Wiadomosc
        fields = ['tekst', 'data_pub']
        exclude = ['autor']
        widgets = {'tekst': TextInput(attrs={'size': 60})}

czat2/czat/views.py
# -*- coding: utf-8 -*-
# czat/views.py
from django.contrib import messages
from django.shortcuts import render
# from django.http import HttpResponse
from django.utils import timezone
from django.views.generic import CreateView, UpdateView

from czat.models import Wiadomosc
from czat.forms import EdytujWiadomoscForm


def index(request):
    """Strona główna aplikacji."""
    # return HttpResponse("Witaj w aplikacji Czat!")
    return render(request, 'index.html')


class DodajWiadomosc(CreateView):
    model = Wiadomosc
    fields = ['tekst', 'data_pub']
    context_object_name = 'wiadomosci'
    success_url = '/dodaj'

    def get_initial(self):
        initial = super(DodajWiadomosc, self).get_initial()
        initial['data_pub'] = timezone.now()

    def get_context_data(self, **kwargs):
        context = super(DodajWiadomosc, self).get_context_data(**kwargs)
        context['wiadomosci'] = Wiadomosc.objects.all()
        return context

    def form_valid(self, form):
        wiadomosc = form.save(commit=False)
        wiadomosc.autor = self.request.user
        wiadomosc.save()
        messages.success(self.request, "Dodano wiadomość!")
        return super(DodajWiadomosc, self).form_valid(form)


class EdytujWiadomosc(UpdateView):
    model = Wiadomosc
    form_class = EdytujWiadomoscForm
    context_object_name = 'wiadomosci'
    template_name = 'wiadomosc_form.html'
    success_url = '/wiadomosci'

    def get_context_data(self, **kwargs):
        context = super(EdytujWiadomosc, self).get_context_data(**kwargs)
        context['wiadomosci'] = Wiadomosc.object.filter(autor=self.request.user)
        return context

    def get_object(self, queryset=None):
        wiadomosc = Wiadomosc.objects.get(id=self.kwargs['pk'])
        return wiadomosc

czat2/czat/templates/czat/index.html
<!-- templates/czat/index.html -->
<html>
  <head></head>
  <body>
    <h1>Witaj w aplikacji Czat!</h1>

    {% if user.is_authenticated %}
        <p>Jesteś zalogowany jako {{ user.username }}.</p>
    {% else %}
        <p><a href="{% url 'czat:rejestruj' %}">Zarejestruj się</a></p>
    {% endif %}

  </body>
</html>

czat2/czat/templates/czat/rejestruj.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Rejestracja</title>
</head>
<body>
    <h1>Rejestracja użytkownika</h1>
    {% if user.is_authenticated %}
        <p>Jesteś już zarejestrowany jako {{ user.username}}.
        <br /><a href="/">Strona główna.</a>
        </p>
    {% else %}
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Zarejestruj</button>
        </form>
    {% endif %}
    <p><a href="{% url 'czat:index' %}">Strona główna</a></p>
</body>
</html>

czat2/czat/templates/index.html
<!-- templates/czat/index.html -->
<html>
  <head></head>
  <body>
    <h1>Witaj w aplikacji Czat!</h1>

    {% if user.is_authenticated %}
        <p>Jesteś zalogowany jako {{ user.username }}.</p>
        <p><a href="{% url 'czat:wyloguj' %}">Wyloguj się.</a></p>
        <p><a href="{% url 'czat:wiadomosc_list' %}">Lista wiadomości</a></p>
        <p><a href="{% url 'czat:wiadomosc_form' %}">Dodaj wiadomość</a></p>
    {% else %}
        <p><a href="{% url 'czat:loguj' %}">Zaloguj się.</a></p>
    {% endif %}

  </body>
</html>

czat2/czat/templates/loguj.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Loguj</title>
</head>
<body>
    <h1>Logowanie użytkownika</h1>
    {% if user.is_authenticated %}
        <p>Jesteś już zalogowany jako {{ user.username }}.
        <br /><a href="/">Strona główna</a></p>
    {% else %}
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Zaloguj</button>
        </form>
    {% endif %}
</body>
</html>

czat2/czat/templates/rejestruj.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Rejestracja</title>
</head>
<body>
    <h1>Rejestracja użytkownika</h1>
    {% if user.is_authenticated %}
        <p>Jesteś już zarejestrowany jako {{ user.username}}.
        <br /><a href="/">Strona główna.</a>
        </p>
    {% else %}
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Zarejestruj</button>
        </form>
    {% endif %}
    <p><a href="{% url 'czat:index' %}">Strona główna</a></p>
</body>
</html>

czat2/czat/templates/wiadomosc_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Wiadomości</title>
</head>
<body>
    <h1>Wiadomości</h1>

    <h2>Dodaj wiadomość:</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Zapisz</button>
    </form>

    <h2>Lista wiadomości:</h2>
    <ol>
        {% for wiadomosc in wiadomosci %}
            <li>
                <strong>{{ wiadomosc.autor.username }}</strong>({{ wiadomosc.data_pub }}):
                <br /> {{ wiadomosc.tekst }}
                {% if wiadomosc.autor.username == user.username %}
                    &bull; <a href="{% url 'czat:edytuj' wiadomosc.id %}">Edytuj</a>
                {% endif %}

                <a href="{% url 'czat:usun' wiadomosc.id %}">Usuń</a>
            </li>

        {% endfor %}
    </ol>

    <p><a href="{% url 'czat:index' %}"></a></p>

</body>
</html>

czat2/czat/templates/wiadomosc_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Wiadomosci</title>
</head>
<body>
    <h1>Wiadomości</h1>

    {% if messages %}
        <ul>
            {% for komunikat in messages %}
                <li>{{ komunikat|capfirst }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <h2>Lista wiadomości:</h2>
    <ol>
        {% for wiadomosc in wiadomosci %}
            <li>
                <strong>{{ wiadomosc.autor.username }}</strong>({{ wiadomosc.data_pub }}):
                <br /> {{ wiadomosc.tekst }}
            </li>
            {% if wiadomosc.autor.username == user.username %}
                &bull; <a href="{% url 'czat:edytuj' wiadomosc.id %}">Edytuj</a>
            {% endif %}
            <a href="{% url 'czat:usun' wiadomosc.id %}">Usuń</a>
        {% endfor %}
    </ol>

    {% if is_paginated %}
        <p>
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">Poprzednie</a>
        {% endif %}
            Strona {{ page_obj.number }} z {{ page_obj.paginator.num_pages }}.
        <span></span>
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Następne</a>
        {% endif %}
        </p>
    {% endif %}

    <p><a href="{% url 'czat:index' %}">Strona główna</a></p>

</body>
</html>

czat2/czat/templates/wiadomosc_usun.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Usuń wiadomość</title>
</head>
<body>
    <h1>Wiadomości</h1>

    <h2>Usuń wiadomość</h2>
    <form method="POST">
      {% csrf_token %}
      <p>Czy na pewno chcesz usunąć wiadomość:<br /><i>{{ object }}</i>?</p>
      <button type="submit">Usuń</button>
    </form>

    <p><a href="{% url 'czat:index' %}">Strona główna</a></p>
</body>
</html>