books/aplikacjaKsiazkowa2/urls.py
# -*- coding: utf-8 -*-

# Examples:
# Function views
#    1. Add an import:  from my_app import views
#    2. Add a URL to urlpatterns:  path('', views.home, name='home')
# Class-based views
#    1. Add an import:  from other_app.views import Home
#    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
# Including another URLconf
#    1. Import the include() function: from django.urls import include, path
#    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))


from django.urls import path, include
from . import views
from rest_framework import routers
from .views import BookViewSet

# router = routers.DefaultRouter()
# router.register(r'book', BookViewSet)


app_name = 'aplikacjaKsiazkowa2'
urlpatterns = [
    path('', views.index, name='index'),
    path('edit/<int:id>', views.edit, name='edit'),
    path('lista', views.lista, name='lista'),
    path('add_book', views.add_book, name='add_book'),
    path('delete/<int:id>', views.delete, name='delete'),
    path('gugle', views.gugle, name='gugle'),
    path('my_api/', views.my_api, name='my_api'),
   # path('api', include(router.urls)),
   # path('api-auth', include('rest_framework.urls', namespace='rest_framework'))
]

books/books/urls.py
# -*- coding: utf-8 -*-
"""books URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('aplikacjaKsiazkowa2.urls')),
    path('admin/', admin.site.urls),
]

books/aplikacjaKsiazkowa2/models.py
# -*- coding: utf-8 -*-
import datetime

from django.db import models
from django.utils import timezone


class Book(models.Model):
    id = models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=200)
    pub_date = models.DateField('data publikacji')
    isbn = models.CharField(max_length=15, null=True, blank=True)
    pages = models.IntegerField(null=True, blank=True)
    cover = models.CharField(max_length=200, null=True, blank=True)
    language = models.CharField(max_length=5, null=True, blank=True)

    def __str__(self):
        return self.title + " - " + self.author

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    class Meta:
        ordering = ['id']

books/aplikacjaKsiazkowa2/views.py
# -*- coding: utf-8 -*-
import datetime

import requests
# from django.core import serializers
from django.core.exceptions import ValidationError
# from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
# from django.urls import reverse
from django.contrib import messages
from django.utils.dateparse import parse_date
# from django.utils.datetime_safe import date
from rest_framework.decorators import api_view
from rest_framework.response import Response

from aplikacjaKsiazkowa2.models import Book

from rest_framework import viewsets, status

# from . import serializer
from .serializer import BookSerializer


class BookViewSet(viewsets.ModelViewSet):
    queryset = Book.objects.all()
    serializer_class = BookSerializer


@api_view(['GET', 'POST'])
def my_api(request):
    """
    Widok REST API posiadający listę książek z wyszukiwaniem i filtrowaniem przy użyciu query string,
    po tytule, autorze, języku oraz zakresie dat.

    Parametry:
    title - tytuł
    author - autor
    language - język
    start_date - data początkowa (format: YYYY-MM-DD)
    end_date - data końcowa (format: YYYY-MM-DD)
    """
    if 'author' in request.GET:
        print("my_api - autor: ")
        author = request.GET['author']
        try:
            data = Book.objects.filter(author__contains=author)
            serial = BookSerializer(data, many=True)
            return Response(serial.data)
        except Book.DoesNotExist:
            return Response(status=status.HTTP_404_NOT_FOUND)

    elif 'title' in request.GET:
        print("my_api - tytuł")
        title = request.GET['title']
        try:
            data = Book.objects.filter(title__contains=title)
            serial = BookSerializer(data, many=True)
            return Response(serial.data)
        except Book.DoesNotExist:
            return Response(status=status.HTTP_404_NOT_FOUND)

    elif 'language' in request.GET:
        print("my_api - język")
        language = request.GET['language']
        try:
            data = Book.objects.filter(language__contains=language)
            serial = BookSerializer(data, many=True)
            return Response(serial.data)
        except Book.DoesNotExist:
            return Response(status=status.HTTP_404_NOT_FOUND)

    elif 'start_date' in request.GET and 'end_date' in request.GET:
        print("my_api - zakres dat")
        try:
            start_date = parse_date(request.GET['start_date'])
            end_date = parse_date(request.GET['end_date'])

            data = Book.objects.filter(pub_date__range=(start_date, end_date))
            serial = BookSerializer(data, many=True)
            return Response(serial.data)
        except ValidationError:
            messages.error(request, "Błąd validacji - zły format daty")
            print("my_api - bad request dla dat.")
            return Response(status=status.HTTP_400_BAD_REQUEST)
        except Book.DoesNotExist:
            return Response(status=status.HTTP_404_NOT_FOUND)

    else:
        print("metoda my_api: {}".format(request))
        try:
            data = Book.objects.order_by('id')
            serial = BookSerializer(data, many=True)
            return Response(serial.data)
        except AttributeError:
            messages.error(request, "Błąd - Attribute error w metodzie my_api")
            print("Blad - Attribute error w metodzie my_api")
            return Response(status=status.HTTP_400_BAD_REQUEST)


def index(request):
    # messages.success(request, "Dzień dobry!")
    return render(request, 'aplikacjaKsiazkowa2/index.html')


def edit(request, id):
    edytowana = get_object_or_404(Book, id=id)
    if request.method == 'POST':
        # messages.success(request, "POST - Edytujesz książkę o id: {}".format(id))
        title = request.POST.get('title')
        author = request.POST.get('author')
        data = request.POST.get('pub_date')
        isbn = request.POST.get('isbn')
        pages = request.POST.get('pages')
        cover = request.POST.get('cover')
        language = request.POST.get('language')

        if edytowana.title != title:
            edytowana.title = title
        if edytowana.author != author:
            edytowana.author = author
        try:
            if edytowana.pub_date != data:
                edytowana.pub_date = data
        except ValidationError:
            messages.error(request, "Podano zły format daty!")
            print("edit - data: {}".format(edytowana.pub_date))
        if edytowana.isbn != isbn:
            edytowana.isbn = isbn
        try:
            if edytowana.pages != pages:
                edytowana.pages = pages
        except ValidationError:
            messages.error(request, "Podano zły format ilości stron!")
            print("edit - strony: {}".format(edytowana.pages))

        if edytowana.cover != cover:
            edytowana.cover = cover
        if edytowana.language != language:
            edytowana.language = language
        try:
            edytowana.save()
        except ValidationError:
            messages.error(request, "Podano zły format danych!")

        data = Book.objects.order_by('id')
        context = {"books_data": data}
        return render(request, 'aplikacjaKsiazkowa2/lista.html', context)

    context = {'book': edytowana}
    return render(request, 'aplikacjaKsiazkowa2/edit.html', context)


def add_book(request):
    if request.method == 'POST':
        print("add_book - POST")
        print(datetime.datetime.now())

        tytul = request.POST.get('title')
        autor = request.POST.get('author')
        pub_date = request.POST.get('pub_date')
        isbn = request.POST.get('isbn')
        pages = request.POST.get('pages')
        cover = request.POST.get('cover')
        lang = request.POST.get('language')
        # print("tytul= {}, {}, {}, {}, {}, {}, {}".format(tytul, autor, pub_date, isbn, pages, cover, lang))
        try:
            nowa = Book(
                title=tytul,
                author=autor,
                pub_date=pub_date,
                isbn=isbn,
                pages=pages,
                cover=cover,
                language=lang
            )
            nowa.save()
        except ValueError:
            print("ValueError")
            messages.error(request, "ValueError.")
        except ValidationError:
            messages.error(request, "ValidationError - błąd typu danych")
        else:
            messages.success(request, "Dodano nową książkę - POST: {}".format(tytul))

        return render(request, 'aplikacjaKsiazkowa2/add_book.html')

    # messages.success(request, "Dodawanie książki - GET.")
    print("add_book - GET")
    print(datetime.datetime.now())
    return render(request, 'aplikacjaKsiazkowa2/add_book.html')


def lista(request):
    if request.method == "POST":
        data = Book.objects.order_by('id')

        if 'd1' in request.POST and 'd2' in request.POST:
            d1 = request.POST.get('d1')
            d2 = request.POST.get('d2')
            print("Lista - wyszukiwanie po przedziale daty: ")
            print('\n lista - metoda POST, d1= {}, d2= {}'.format(d1, d2))
            try:
                data = Book.objects.filter(pub_date__range=(d1, d2))
            except ValidationError:
                messages.warning(request, "ValidationError - zła data! Podaj prawidłowy zakres!")
            else:
                if not data.exists():
                    messages.warning(request, "Pusty zakres przeszukiwania dat!")
                context = {'books_data': data}
                return render(request, 'aplikacjaKsiazkowa2/lista.html', context)

        if 'language' in request.POST:
            jezyk = request.POST.get('language')
            print('Lista - Wyszukiwanie po języku: {}  \n'.format(jezyk))
            try:
                data = Book.objects.filter(language__contains=jezyk)
            except ValidationError:
                messages.warning(request, "ValidationError - zły język! Podaj prawidłowe dane!")
            else:
                if not data.exists():
                    messages.warning(request, "Brak książek tego języka")
                context = {'books_data': data}
                return render(request, 'aplikacjaKsiazkowa2/lista.html', context)

        if 'title' in request.POST:
            tytul = request.POST.get('title')
            print('Lista - wyszukiwanie po tytule: {} \n'.format(tytul))
            try:
                data = Book.objects.filter(title__contains=tytul)
            except ValidationError:
                messages.warning(request, "ValidationError - zły tytuł! Podaj prawidłowe dane!")
            else:
                if not data.exists():
                    messages.warning(request, "Brak książek o tym tytule")
                context = {'books_data': data}
                return render(request, 'aplikacjaKsiazkowa2/lista.html', context)

        if 'author' in request.POST:
            autor = request.POST.get('author')
            print("lista - wyszukiwanie po autorze: {} \n ".format(autor))
            try:
                data = Book.objects.filter(author__contains=autor)
            except ValidationError:
                messages.warning(request, "ValidationError - zły autor! Podaj prawidłowe dane!")
            else:
                if not data.exists():
                    messages.warning(request, "Brak książek tego autora")
                context = {'books_data': data}
                return render(request, 'aplikacjaKsiazkowa2/lista.html', context)

        context = {'books_data': data}
        print('\n lista - POST - koniec \n')
        return render(request, 'aplikacjaKsiazkowa2/lista.html', context)

    data = Book.objects.order_by('id')
    context = {"books_data": data}
    return render(request, 'aplikacjaKsiazkowa2/lista.html', context)


def delete(request, id):
    print("*************** metoda delete **************** ")

books/aplikacjaKsiazkowa2/templates/aplikacjaKsiazkowa2/add_book.html
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <title>Edycja książki:</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
</head>
<body>
    {% if messages %}
        <ul>
            {% for komunikat in messages %}
                <li>{{ komunikat|capfirst }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <div class="container mv-5 mt-3">
        <table class="table table-striped table-bordered mydatatable" style="width: 100%">
	        <thead>
                <tr>
                    <th>Id</th>
                    <th>Tytuł</th>
                    <th>Autor</th>
                    <th>Data publikacji</th>
                    <th>ISBN</th>
                    <th>Liczba stron</th>
                    <th>Link do okładki</th>
                    <th>Język publikacji</th>
                </tr>
	        </thead>
            <tbody>
                <tr>
				    <form action="{% url 'aplikacjaKsiazkowa2:add_book' %}" method="POST">
                   	  <th></th>
                      <th>
                          <input type="text" class="form-control" id="title" placeholder="Tytuł" name="title">
              		  </th>
                      <th>
                          <input type="text" class="form-control" id="author" placeholder="Autor" name="author">
                      </th>
                      <th>
                          <input type="date" class="form-control" id="pub_date" placeholder="Data publikacji" name="pub_date">
                      </th>
                      <th>
                          <input type="text" class="form-control" id="isbn" placeholder="ISBN" name="isbn">
                      </th>
                      <th>
                          <input type="number" class="form-control" id="pages" placeholder="Liczba stron" name="pages">
                      </th>
                      <th>
                          <input type="text" class="form-control" id="cover" placeholder="Link do okładki" name="cover">
                      </th>
                      <th>
                          <input type="text" class="form-control" id="language" placeholder="Język" name="language">
                      </th>
                      <th>
                          {% csrf_token %}
                          <button type="submit" class="btn btn-primary" >Zapisz książkę</button>
                      </th>
                    </form>
                </tr>
            </tbody>
	    </table>
    </div>

    <div class="container">
        <form action="{% url 'aplikacjaKsiazkowa2:index' %}">
            <div>
                <button type="submit" class="btn btn-primary">Strona główna</button>
            </div>
        </form>
        <br>
        <form action="{% url 'aplikacjaKsiazkowa2:lista' %}">
            <div>
                <button type="submit" class="btn btn-primary">Lista książek</button>
            </div>
        </form>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.botstrap4.min.js"></script>

</body>
</html>

books/aplikacjaKsiazkowa2/templates/aplikacjaKsiazkowa2/edit.html
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <title>Edycja książki:</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
</head>
<body>
    <div class="container mv-5 mt-3">
        <table class="table table-striped table-bordered mydatatable" style="width: 100%">
	        <thead>
                <tr>
                    <th>Id</th>
                    <th>Tytuł</th>
                    <th>Autor</th>
                    <th>Data publikacji</th>
                    <th>ISBN</th>
                    <th>Liczba stron</th>
                    <th>Link do okładki</th>
                    <th>Język publikacji</th>
                </tr>
	        </thead>
            <tbody>
                <tr>
                    <th scope="row">{{ book.id }}</th>
                    <th scope="row">{{ book.title }}</th>
                    <th scope="row">{{ book.author }}</th>
                    <th scope="row">{{ book.pub_date }}</th>
                    <th scope="row">{{ book.isbn }}</th>
                    <th scope="row">{{ book.pages }}</th>
                    <th scope="row">{{ book.cover }}</th>
                    <th scope="row">{{ book.language }}</th>
                </tr>
            </tbody>
            <tfoot>
				<form action="./{{ book.id }}" method="POST" id=book.id>
                   <tr>
                   	  <th scope="row">{{ book.id }}</th>
                      <th>
                          <input type="text" class="form-control" id="title" placeholder="{{ book.title }}" name="title" value="{{ book.title }}">
              		  </th>
                      <th>
                          <input type="text" class="form-control" id="author" placeholder="Autor" name="author" value="{{ book.author }}">
                      </th>
                      <th>
                          <input type="date" class="form-control" id="pub_date" placeholder="Data publikacji" name="pub_date" content="{{ book.pub_date }}" value="{{ book.pub_date }}">
                      </th>
                      <th>
                          <input type="text" class="form-control" id="isbn" placeholder="ISBN" name="isbn" value="{{ book.isbn }}">
                      </th>
                      <th>
                          <input type="number" class="form-control" id="pages" placeholder="Liczba stron" name="pages" content="{{ book.pages }}" value="{{ book.pages }">
                      </th>
                      <th>
                          <input type="text" class="form-control" id="cover" placeholder="Link do okładki" name="cover" value="{{ book.cover }}">
                      </th>
                      <th>
                          <input type="text" class="form-control" id="language" placeholder="Język" name="language" value="{{ book.language }}">
                      </th>
                      <th>
                           <div>
                                {% csrf_token %}
                                <button type="submit" class="btn btn-primary">Zapisz</button>
                           </div>
                      </th>
                   </tr>

                </form>
            </tfoot>
	    </table>
    </div>
    <div class="container">
        <form action="{% url 'aplikacjaKsiazkowa2:index' %}">
            <div>
                <button type="submit" class="btn btn-primary">Strona główna</button>
            </div>
        </form>
        <br>
        <form action="{% url 'aplikacjaKsiazkowa2:lista' %}">
            <div>
                <button type="submit" class="btn btn-primary">Lista książek</button>
            </div>
        </form>
        <br>
        <form action="{% url 'aplikacjaKsiazkowa2:add_book' %}">
            <div>
                <button type="submit" class="btn btn-primary">Nowa książka</button>
            </div>
        </form>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.botstrap4.min.js"></script>

</body>
</html>

books/aplikacjaKsiazkowa2/templates/aplikacjaKsiazkowa2/gugleApi.html
<!DOCTYPE html "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <title>Google Books Embedded Viewer API Example</title>
    <script type="text/javascript" src="https://www.google.com/books/jsapi.js"></script>
    <script type="text/javascript">
      google.books.load();

      function initialize() {
        var viewer = new google.books.DefaultViewer(document.getElementById('viewerCanvas'));
        viewer.load('ISBN:9788324403875');
      }

      google.books.setOnLoadCallback(initialize);
    </script>
  </head>
  <body>
    <div id="viewerCanvas" style="width: 600px; height: 500px"></div>
  </body>
</html>

<!DOCTYPE html>
<html lang="en">
<head>
  <title>Google API</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <style>
    .fakeimg {
        height: 200px;
        background: #aaa;
    }
  </style>
</head>
<body>

    <div class="container" style="margin-top:30px">
        <form action="{% url 'aplikacjaKsiazkowa2:gugle' %}" method="POST" >
            Podaj słowo kluczowe, dla którego chcesz wyszukać dostępne książki w Google API.
            <br>
            Wszystkie znalezione zostaną dodane do bazy.
            <div>
            {% csrf_token %}
                <button type="submit" class="btn btn-primary">Wyszukaj w Google API</button><br>
                <input type="text" class="form-control" name="terms"/>
            </div>
        </form>
        <form>

        </form>

    </div>


    <div class="container" style="margin-top:30px">
        <div class="row">
            <div class="col-sm-4">
                <ul class="nav nav-pills flex-column">
                    <li class="nav-item">
                        <a class="nav-link" href="lista">Lista książek</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="add_book">Dodaj książkę</a>
                    </li>

                </ul>
                <hr class="d-sm-none">
            </div>
        </div>
    </div>


</body>
<footer>
  <div class="jumbotron text-center" style="margin-bottom:0">
        <p>Strona przykładowa do rekrutacji do STX Next, październik 2021</p>
    </div>
</footer>
</html>

books/aplikacjaKsiazkowa2/templates/aplikacjaKsiazkowa2/lista.html
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <title>Lista książek</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
</head>
<body>
    {% if messages %}
        <ul>
            {% for komunikat in messages %}
                <li>{{ komunikat|capfirst }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <div class="container mv-5 mt-3">
        <table class="table table-striped table-bordered mydatatable" style="width: 100%">
	        <thead>
                <tr>
                    <th>Id</th>
                    <th>Tytuł</th>
                    <th>Autor</th>
                    <th>Data publikacji</th>
                    <th>ISBN</th>
                    <th>Liczba stron</th>
                    <th>Link do okładki</th>
                    <th>Język publikacji</th>
                    <th>Edycja</th>
                    <th>Usuwanie</th>
                </tr>
	        </thead>
	        <tbody>
                {% for book in books_data %}
                <tr>
                    <th scope="row">{{ book.id }}</th>
                    <th scope="row">{{ book.title }}</th>
                    <th scope="row">{{ book.author }}</th>
                    <th scope="row">{{ book.pub_date }}</th>
                    <th scope="row">{{ book.isbn }}</th>
                    <th scope="row">{{ book.pages }}</th>
                    <th scope="row">{{ book.cover }}</th>
                    <th scope="row">{{ book.language }}</th>
                    <th scope="row">
                        <form action="{% url 'aplikacjaKsiazkowa2:edit' id=book.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-warning">Edytuj</button>
                        </form>
                    </th>
                    <th scope="row">
                        <form action="{% url 'aplikacjaKsiazkowa2:delete' id=book.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger">Usuń</button>
                        </form>
                    </th>
                </tr>
                {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <th>Id</th>
                    <th>Tytuł</th>
                    <th>Autor</th>
                    <th>Data publikacji</th>
                    <th>ISBN</th>
                    <th>Liczba stron</th>
                    <th>Link do okładki</th>
                    <th>Język publikacji</th>
                    <th>Edycja</th>
                    <th>Usuwanie</th>
                </tr>
	        </tfoot>
	    </table>
    </div>

    <div class="container">
        <form action="{% url 'aplikacjaKsiazkowa2:lista' %}" method="POST" >
            <div>
                {% csrf_token %}
                <button type="submit" class="btn btn-primary">Wybierz zakres dat</button><br>
                Data początkowa:<input type="date" class="form-control" id="d1" name="d1"/>
                Data końcowa:<input type="date" class="form-control" id="d2" name="d2"/>
            </div>
        </form>
        <form action="{% url 'aplikacjaKsiazkowa2:lista' %}" method="POST" >
            <br>
            <div>
            {% csrf_token %}
                <button type="submit" class="btn btn-primary">Wyszukaj tytuł</button><br>
                <input type="text" class="form-control" id="t_search" name="title" />
            </div>
        </form>
            <br>
        <form action="{% url 'aplikacjaKsiazkowa2:lista' %}" method="POST" >
            <div>
            {% csrf_token %}
                <button type="submit" class="btn btn-primary">Wyszukaj autora</button><br>
                <input type="text" class="form-control" id="a_search" name="author" />
            </div>
        </form>
            <br>
        <form action="{% url 'aplikacjaKsiazkowa2:lista' %}" method="POST" >
            <div>
            {% csrf_token %}
                <button type="submit" class="btn btn-primary">Wyszukaj język</button><br>
                <input type="text" class="form-control" id="l_search" name="language" />
            </div>
            <br>
        </form>

        <form action="{% url 'aplikacjaKsiazkowa2:index' %}">
            <div>
                <button type="submit" class="btn btn-primary">Strona główna</button>
            </div>
        </form>
        <br>
        <form action="{% url 'aplikacjaKsiazkowa2:add_book' %}">
            <div>
                <button type="submit" class="btn btn-primary">Dodaj książkę</button>
            </div>
        </form>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.botstrap4.min.js"></script>

    <script>
        $('.mydatatable').DataTable({
            pagingType: 'full_numbers',
            searching: true,
        });
    </script>

</body>
</html>